[project]
name = "test"
version = "0.0.1"
description = ""
requires-python = ">= 3.7.2,<4.0"
dependencies = [
    "package_a @ file:///${PROJECT_ROOT}/package_a",
    "package_b @ file:///${PROJECT_ROOT}/package_b",
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"